### ISSUE TITLE
Javascripts must be served over HTTPS

### ISSUE THREAD

**Issue by mustakimali** [staxmanade/ExceptionMessageBeautifier#1]
![image](https://user-images.githubusercontent.com/1546896/30586706-c31685e2-9d28-11e7-8fdc-d804b350fcd6.png)

Please serve javascript over HTTPS, this is in incredibly useful tool so here is a snippet you can use straightaway.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.4/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.4/angular-animate.min.js"></script>
```

Thanks for the tool. 👍

**Comment by staxmanade** [comment]
Thanks for pointing this out... I'll get it updated.

**Comment by staxmanade** [comment]
Appreciate the notification. It's been fixed.
